package:
  name: ska3-dev
  version: 0.1

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
   - agasc
   - alabaster
   - annie
   - asn1crypto
   - astroid
   - astropy
   - babel
   - beautifulsoup4
   - bleach
   - certifi
   - cffi
   - chandra.cmd_states
   - chandra.maneuver
   - chandra.time
   - chandra_aca
   - chardet
   - configobj
   - cryptography
   - curl
   - cxotime
   - cycler
   - cython
   - db
   - dbus
   - decorator
   - django
   - docutils
   - entrypoints
   - expat
   - fontconfig
   - freetype
   - git
   - glib
   - gst-plugins-base
   - gstreamer
   - h5py
   - hdf5
   - hopper
   - html5lib
   - icu
   - idna
   - imagesize
   - ipykernel
   - ipyparallel
   - ipython
   - ipython_genutils
   - ipywidgets
   - isort
   - jbig
   - jedi
   - jinja2
   - jpeg
   - jsonschema
   - jupyter
   - jupyter_client
   - jupyter_console
   - jupyter_core
   - kadi
   - krb5
   - lazy-object-proxy
   - libffi
   - libgcc
   - libgfortran
   - libiconv
   - libpng
   - libsodium
   - libssh2
   - libtiff
   - libxcb
   - libxml2
   - libxslt
   - line_profiler
   - llvmlite
   - lxml
   - markupsafe
   - matplotlib
   - maude
   - mica
   - mistune
   - mkl
   - mpi4py
   - mpich2
   - nbconvert
   - nbformat
   - networkx
   - nose
   - notebook
   - numba
   - numexpr
   - numpy
   - numpydoc
   - olefile
   - openssl
   - packaging
   - pandas
   - pandocfilters
   - paramiko
   - parse_cm
   - path.py
   - pcre
   - pep8
   - pexpect
   - pickleshare
   - pillow
   - pip
   - ply
   - prompt_toolkit
   - psutil
   - ptyprocess
   - py
   - pyasn1
   - pycodestyle
   - pycosat
   - pycparser
   - pycrypto
   - pyflakes
   - pygments
   - pylint
   - pyopenssl
   - pyparsing
   - pyqt
   - pytables
   - pytest
   - python
   - python-dateutil
   - pytz
   - pyyaks
   - pyyaml
   - pyzmq
   - qt
   - qtawesome
   - qtconsole
   - qtpy
   - quaternion
   - readline
   - requests
   - rope
   - ruamel_yaml
   - runipy
   - scikit-learn
   - scipy
   - setuptools
   - sherpa
   - simplegeneric
   - singledispatch
   - sip
   - six
   - ska.arc5gl
   - ska.astro
   - ska.dbi
   - ska.engarchive
   - ska.file
   - ska.ftp
   - ska.matplotlib
   - ska.numpy
   - ska.parsecm
   - ska.quatutil
   - ska.shell
   - ska.sun
   - ska.tdb
   - ska3-core
   - ska3-flight
   - ska3-template
   - ska_path
   - snowballstemmer
   - sphinx
   - sphinxcontrib
   - sphinxcontrib-websupport
   - spyder
   - sqlalchemy
   - sqlite
   - tables3_api
   - terminado
   - testpath
   - testr
   - tk
   - tornado
   - traitlets
   - wcwidth
   - wheel
   - widgetsnbextension
   - wrapt
   - xija
   - xz
   - yaml
   - zeromq
   - zlib
