package:
  name: kadi
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/kadi


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - astropy
    - django >=3.0,<4.0
    - jinja2
    - matplotlib
    - numpy
    - tqdm
    - plotly
    - acdc
    - agasc
    - chandra_aca
    - chandra_cmd_states
    - chandra_maneuver
    - chandra_time
    - cheta
    - cxotime
    - kadi
    - mica
    - maude
    - parse_cm
    - proseco
    - pyyaks
    - quaternion
    - ska_file
    - ska_ftp
    - ska_helpers
    - ska_matplotlib
    - ska_numpy
    - ska_sun
    - ska_tdb
    - testr

test:
  imports:
    - kadi


about:
  home: https://github.com/sot/kadi
  license: BSD
  summary: kadi
