package:
  name: kadi
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .
  entrypoints:
    - get_chandra_states=kadi.commands.states:get_chandra_states
    - kadi_update_cmds_v2=kadi.scripts.update_cmds_v2:main
    - kadi_update_events=kadi.scripts.update_events:main
    - kadi_validate_states=kadi.scripts.validate_states:main

source:
  path: {{ SKA_TOP_SRC_DIR }}/kadi


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - django >=3.0,<4.0

test:
  imports:
    - kadi


about:
  home: https://github.com/sot/kadi
  license: BSD
  summary: kadi
