package:
  name: starcheck
  version:  {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/starcheck


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - python
    - pip
    - setuptools
    - testr
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - perl ==5.26.2
    - perl-core-deps
    - perl-ska-classic
    - perl-ska-convert
    - perl-chandra-time
    - chandra_aca
    - hopper
    - agasc
    - proseco
    - ska.matplotlib
    - testr

test:
  imports:
    - starcheck


about:
  home: git@github.com:sot/starcheck

