package:
  name: ska.file  # lower case name of package, may contain '-' but no spaces
  version: {{ GIT_DESCRIBE_TAG }}{% if GIT_DESCRIBE_NUMBER != '0'%}_dev{{GIT_DESCRIBE_NUMBER}}{% endif %}


build:
  noarch: python
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.File



requirements:
  build:
    - python
    - pip <10.0

  run:
    - python


test:
  imports:
    - Ska.File

about:
  home: https://github.com/sot/Ska.File
