
package:
  name: ska.shell  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Shell

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - ska_helpers

  run:
    - python
    - six
    - pexpect
    - testr
    - ska_helpers

test:
  imports:
    - Ska.Shell

about:
  home: https://github.com/sot/Ska.Shell

