package:
  name: sherpa
  version: {{ environ.get('SHERPA_TAG') }}

source:
  git_rev: {{ environ.get('SHERPA_TAG') }}
  git_url: https://github.com/sherpa/sherpa.git

requirements:
  build:
    - python=3.11
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - conda-build
    - conda-verify
    - bison
    - setuptools <60.0.0

  host:
    - python 3.11
    - setuptools <60.0.0
    - pip
    - numpy 1.21.* # [py<=310]
    - numpy 1.23.* # [py>310]
    - matplotlib >3.3.0

  run:
    - python
    - {{ pin_compatible('numpy') }}

about:
  home: https://github.com/sherpa/sherpa
  license: GPL3
  license_file: LICENSE

