package:
 name: sherpa
 version: {{ SKA_PKG_VERSION }}

source:
 path: {{ SKA_TOP_SRC_DIR }}/sherpa
 patches:
  - multiprocess_patch.txt # [osx-64]

requirements:
 build:
  - {{ compiler('cxx') }}
  - {{ compiler('c') }}
  - make
  - bison
  - flex

 host:
  - python
  - numpy
  - setuptools
  - six

 run:
  - python
  - numpy >1.11
  - setuptools
  - pytest
  - six

test:
  imports:
    - sherpa.ui

  commands:
    - sherpa_smoke

about:
 home: https://github.com/sherpa/sherpa
 summary: Sherpa is the CIAO modeling and fitting application. It enables the user to construct complex models from simple definitions and fit those models to data, using a variety of statistics and optimization methods
 license: GPLv3

