package:
  name: ska.file  # lower case name of package, may contain '-' but no spaces
  version: {{ SKA_PKG_VERSION }}


build:
  noarch: python
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.File



requirements:
  build:
    - python
    - pip <10.0
    - setuptools_scm

  run:
    - python


test:
  imports:
    - Ska.File

about:
  home: https://github.com/sot/Ska.File
