package:
  name: ska_helpers
  version: {{ SKA_PKG_VERSION }}


build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/ska_helpers



requirements:
  build:
    - python
    - pytest
    - setuptools
    - setuptools_scm
  run:
    - python


about:
  home: https://github.com/sot/ska_helpers
