package:
  name: skare3_tools
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/skare3_tools


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - setuptools_scm
    - pyyaml
    - jinja2
    - google-auth-oauthlib
    - google-api-python-client
    - sphinx-argparse
    - keyring
    - jinja2

about:
  home: https://github.com/sot/skare3_tools
