---
package:
  name: ska3-flight
  version: 2023.3

build:
  noarch: generic

requirements:
  run:
    - aca_view ==0.12.0
    - acis_thermal_check ==4.6.0
    - acispy ==2.5.0
    - agasc ==4.15.0
    - backstop_history ==3.2.1
    - chandra_cmd_states ==4.0.0
    - chandra_maneuver ==4.0.0
    - chandra_time ==4.1.2
    - chandra_aca ==4.41.0
    - cheta ==4.59.0
    - cxotime ==3.6.0
    - find_attitude ==3.4.3
    - fot-matlab ==2.2.0
    - hopper ==4.5.4
    - kadi ==7.4.1
    - maude ==3.11.1
    - mica ==4.33.0
    - parse_cm ==3.10.0
    - proseco ==5.9.0
    - pyyaks ==4.5.0
    - quaternion ==4.1.1
    - ska_arc5gl ==4.0.1
    - ska_astro ==4.0.0
    - ska_dbi ==5.0.0
    - ska_file ==4.0.0
    - ska_ftp ==4.0.0
    - ska_matplotlib ==4.0.1
    - ska_numpy ==4.0.1
    - ska_parsecm ==4.0.0
    - ska_quatutil ==4.0.0
    - ska_shell ==4.0.1
    - ska_sun ==3.10.1
    - ska_tdb ==4.0.0
    - ska3-core ==2023.3
    - ska3-template ==2022.06.02
    - ska_helpers ==0.10.4
    - ska_path ==3.1.2
    - ska_sync ==4.10.1
    - skare3_tools ==1.0.10
    - sparkles ==4.22.2
    - starcheck ==14.2.1
    - testr ==4.11.3
    - xija ==4.30.0
