package:
  name: ska3-flight
  version: 2020.01.15

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - ska3-core ==2020.01.10
    - ska3-template ==2019.09.03
    - acdc ==4.4.1
    - agasc ==4.8.0
    - acisfp_check ==v2.7.0
    - acis_taco ==4.1.0
    - acis_thermal_check ==v2.9.0
    - annie ==0.9.1
    - backstop_history ==v1.1.0
    - chandra_aca ==4.28.1
    - chandra.cmd_states ==3.15.1
    - chandra.maneuver ==3.7.2
    - chandra.time ==3.20.4
    - cxotime ==3.1.1
    - dea_check ==v2.3.0
    - dpa_check ==v2.5.0
    - find_attitude ==3.3.2
    - hopper ==4.4.1
    - jplephem ==2.8
    - kadi ==5.0.0
    - maude ==3.3.1
    - mica ==4.20.0
    - parse_cm ==3.5.1
    - proseco ==4.7.2
    - psmc_check ==v1.2.0
    - pyyaks ==4.4.1
    - quaternion ==3.5.0
    - ska.arc5gl ==3.1.2
    - ska.astro ==3.2.2
    - ska.dbi ==4.0.1
    - ska.engarchive ==4.47.3
    - ska.file ==3.4.2
    - ska.ftp ==3.5.2
    - ska.numpy ==3.8.2
    - ska.matplotlib ==3.11.3
    - ska.parsecm ==3.3.2
    - ska_helpers ==0.1.0
    - ska_path ==3.1.1
    - ska_sync ==4.6.0
    - ska.quatutil ==3.3.2
    - ska.shell ==3.4.0
    - ska.sun ==3.5.1
    - ska.tdb ==3.5.2
    - sparkles ==4.4.0
    - starcheck ==13.5.1
    - tables3_api ==0.1.1
    - testr ==4.3.1
    - xija ==4.15
