{% set data = load_setup_py_data() %}

package:
  name: ska.sun  # lower case name of package, may contain '-' but no spaces
  version: {{ data.get('version') }}


build:
  preserve_egg_dir: yes
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Sun



requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - ska.quatutil
    - chandra.time
    - quaternion

test:
  imports:
    - Ska.Sun

about:
  home: https://github.com/sot/Ska.Sun
