---
package:
  name: ska3-core
  version: 2022.1

requirements:
  run:
    - _libgcc_mutex ==0.1  # [linux]
    - _openmp_mutex ==4.5  # [linux]
    - alabaster ==0.7.12
    - anyio ==3.4.0  # [linux or osx]
    - appnope ==0.1.2  # [osx]
    - argon2-cffi ==21.1.0  # [linux or osx]
    - asgiref ==3.4.1
    - astroid ==2.9.0  # [linux or osx]
    - astropy ==5.0
    - astropy-healpix ==0.6  # [linux or osx]
    - astropy-sphinx-theme ==1.1  # [linux or osx]
    - async_generator ==1.10  # [linux or osx]
    - atomicwrites ==1.4.0  # [win]
    - attrs ==21.2.0
    - autopep8 ==1.6.0  # [linux or osx]
    - babel ==2.9.1
    - backcall ==0.2.0
    - backports ==1.0  # [linux or osx]
    - backports.zoneinfo ==0.2.1  # [linux or osx]
    - bcrypt ==3.2.0
    - beautifulsoup4 ==4.10.0
    - blas ==1.0  # [osx or win]
    - blas ==1.1  # [linux]
    - bleach ==4.1.0  # [linux or osx]
    - blinker ==1.4  # [linux or osx]
    - blosc ==1.21.0
    - bokeh ==2.4.2  # [linux or osx]
    - brotli ==1.0.9
    - brotlipy ==0.7.0
    - bzip2 ==1.0.8
    - c-ares ==1.18.1  # [linux or osx]
    - ca-certificates ==2021.10.26
    - certifi ==2021.10.8
    - cffi ==1.14.0
    - chardet ==3.0.4
    - colorama ==0.4.4
    - commonmark ==0.9.1
    - conda ==4.8.3
    - conda-build ==3.21.7
    - conda-package-handling ==1.6.1
    - configobj ==5.0.6
    - cryptography ==2.9.2
    - cycler ==0.11.0
    - cython ==0.29.25  # [linux or osx]
    - dbus ==1.13.18  # [linux or osx]
    - debugpy ==1.5.1
    - decorator ==5.1.0
    - defusedxml ==0.7.1  # [linux or osx]
    - django ==3.1.7
    - docutils ==0.17.1
    - docxtpl ==0.11.5  # [linux or osx]
    - entrypoints ==0.3
    - expat ==2.4.1  # [linux or osx]
    - filelock ==3.4.0
    - flake8 ==4.0.1  # [linux or osx]
    - font-ttf-dejavu-sans-mono ==2.37  # [linux]
    - font-ttf-inconsolata ==3.000  # [linux]
    - font-ttf-source-code-pro ==2.038  # [linux]
    - font-ttf-ubuntu ==0.83  # [linux]
    - fontconfig ==2.13.1  # [linux]
    - fonts-conda-forge ==1  # [linux]
    - fonttools ==4.28.4
    - freetype ==2.10.4  # [win]
    - freetype ==2.11.0  # [linux or osx]
    - future ==0.18.2
    - gettext ==0.21.0  # [osx]
    - giflib ==5.2.1  # [linux or osx]
    - gitdb ==4.0.9
    - gitpython ==3.1.24
    - glib ==2.69.1  # [linux or osx]
    - glob2 ==0.7
    - gst-plugins-base ==1.14.0  # [linux]
    - gstreamer ==1.14.0  # [linux]
    - h5py ==2.10.0  # [win]
    - h5py ==3.6.0  # [linux or osx]
    - hdf5 ==1.10.4  # [win]
    - hdf5 ==1.10.6  # [linux or osx]
    - icc_rt ==2019.0.0  # [win]
    - icu ==58.2  # [linux]
    - icu ==64.2  # [win]
    - icu ==68.2  # [osx]
    - idna ==2.10
    - imagesize ==1.3.0
    - importlib-metadata ==4.2.0  # [linux or osx]
    - importlib-metadata ==4.8.2  # [win]
    - importlib_metadata ==4.2.0  # [linux or osx]
    - importlib_resources ==5.4.0  # [linux or osx]
    - iniconfig ==1.1.1
    - intel-openmp ==2021.4.0  # [osx or win]
    - ipykernel ==6.5.1  # [win]
    - ipykernel ==6.6.0  # [linux or osx]
    - ipympl ==0.8.4  # [linux or osx]
    - ipyparallel ==8.0.0
    - ipython ==7.30.1
    - ipython_genutils ==0.2.0
    - ipywidgets ==7.6.5  # [linux or osx]
    - isort ==5.10.1  # [linux or osx]
    - jbig ==2.1  # [osx]
    - jedi ==0.18.1
    - jeepney ==0.7.1  # [linux]
    - jinja2 ==2.11.3
    - jira ==3.1.1  # [linux or osx]
    - joblib ==1.1.0  # [linux or osx]
    - jpeg ==9d
    - jplephem ==2.16  # [linux or osx]
    - json5 ==0.9.6  # [linux or osx]
    - jsonschema ==4.3.0  # [linux or osx]
    - jupyter ==1.0.0  # [linux or osx]
    - jupyter_client ==7.1.0
    - jupyter_console ==6.4.0  # [linux or osx]
    - jupyter_core ==4.9.1
    - jupyter_server ==1.13.1  # [linux or osx]
    - jupyterlab ==3.2.5  # [linux or osx]
    - jupyterlab_pygments ==0.1.2  # [linux or osx]
    - jupyterlab_server ==2.9.0  # [linux or osx]
    - jupyterlab_widgets ==1.0.2  # [linux or osx]
    - kaleido-core ==0.2.1  # [linux or osx]
    - keyring ==23.4.0  # [linux or osx]
    - kiwisolver ==1.3.2
    - krb5 ==1.18.2  # [win]
    - krb5 ==1.19.2  # [linux or osx]
    - lazy-object-proxy ==1.7.1  # [linux or osx]
    - lcms2 ==2.12  # [linux or osx]
    - ld_impl_linux-64 ==2.33.1  # [linux]
    - lerc ==2.2.1  # [osx]
    - libarchive ==3.4.2  # [linux or win]
    - libarchive ==3.5.2  # [osx]
    - libblas ==3.9.0
    - libcblas ==3.9.0
    - libclang ==11.1.0  # [osx]
    - libclang ==9.0.1  # [win]
    - libcurl ==7.71.1  # [win]
    - libcurl ==7.80.0  # [linux or osx]
    - libcxx ==12.0.1  # [osx]
    - libdeflate ==1.7  # [osx]
    - libedit ==3.1.20210714  # [linux]
    - libedit ==3.1.20210910  # [osx]
    - libev ==4.33  # [linux or osx]
    - libffi ==3.3  # [linux or osx]
    - libgcc-ng ==11.2.0  # [linux]
    - libgfortran ==5.0.0  # [osx]
    - libgfortran-ng ==11.2.0  # [linux]
    - libgfortran5 ==11.2.0  # [linux]
    - libgfortran5 ==9.3.0  # [osx]
    - libgomp ==11.2.0  # [linux]
    - libiconv ==1.15  # [linux or win]
    - libiconv ==1.16  # [osx]
    - liblapack ==3.9.0
    - liblief ==0.11.5
    - libllvm11 ==11.1.0  # [linux or osx]
    - libnghttp2 ==1.46.0  # [linux or osx]
    - libopenblas ==0.3.18  # [linux or osx]
    - libpng ==1.6.37
    - libpq ==12.2  # [win]
    - libpq ==12.9  # [linux]
    - libpq ==13.3  # [osx]
    - libsodium ==1.0.18  # [linux or osx]
    - libsolv ==0.7.14  # [osx]
    - libsolv ==0.7.16  # [linux]
    - libsolv ==0.7.17  # [win]
    - libssh2 ==1.9.0
    - libstdcxx-ng ==11.2.0  # [linux]
    - libtiff ==4.2.0  # [linux or win]
    - libtiff ==4.3.0  # [osx]
    - libuuid ==1.0.3  # [linux]
    - libuv ==1.40.0  # [osx]
    - libwebp ==1.2.0  # [linux or osx]
    - libwebp ==1.2.1  # [win]
    - libwebp-base ==1.2.0  # [linux or osx]
    - libwebp-base ==1.2.1  # [win]
    - libxcb ==1.14  # [linux]
    - libxml2 ==2.9.10  # [win]
    - libxml2 ==2.9.12  # [linux or osx]
    - libxslt ==1.1.33  # [osx]
    - libxslt ==1.1.34  # [linux]
    - libzlib ==1.2.11  # [linux]
    - line_profiler ==3.3.1  # [linux or osx]
    - llvm-openmp ==12.0.1  # [osx]
    - llvmlite ==0.36.0  # [win]
    - llvmlite ==0.37.0  # [linux or osx]
    - lxml ==4.7.1  # [linux or osx]
    - lz4-c ==1.9.2  # [linux or win]
    - lz4-c ==1.9.3  # [osx]
    - lzo ==2.10
    - m2w64-gcc-libgfortran ==5.3.0  # [win]
    - m2w64-gcc-libs ==5.3.0  # [win]
    - m2w64-gcc-libs-core ==5.3.0  # [win]
    - m2w64-gmp ==6.1.0  # [win]
    - m2w64-libwinpthread-git ==5.0.0.4634.697f757  # [win]
    - mamba ==0.4.2  # [osx]
    - mamba ==0.5.1  # [linux or win]
    - markupsafe ==2.0.1
    - mathjax ==2.7.7  # [linux or osx]
    - matplotlib ==3.5.1
    - matplotlib-base ==3.5.1
    - matplotlib-inline ==0.1.3
    - mccabe ==0.6.1  # [linux or osx]
    - menuinst ==1.4.16  # [win]
    - mistune ==0.8.4  # [linux or osx]
    - mkl ==2021.4.0  # [osx or win]
    - mkl-service ==2.4.0  # [osx or win]
    - mkl_fft ==1.3.1  # [osx]
    - mkl_random ==1.2.2  # [osx]
    - mock ==4.0.3
    - more-itertools ==8.12.0  # [win]
    - mpld3 ==0.5.7  # [linux or osx]
    - msys2-conda-epoch ==20160418  # [win]
    - munkres ==1.1.4
    - mysql-common ==8.0.25  # [osx]
    - mysql-libs ==8.0.25  # [osx]
    - nb_conda ==2.2.1  # [linux or osx]
    - nb_conda_kernels ==2.3.1  # [linux or osx]
    - nbclassic ==0.3.4  # [linux or osx]
    - nbclient ==0.5.9  # [linux or osx]
    - nbconvert ==6.3.0  # [linux or osx]
    - nbformat ==5.1.3  # [linux or osx]
    - ncurses ==6.2  # [linux]
    - ncurses ==6.3  # [osx]
    - nest-asyncio ==1.5.4
    - networkx ==2.6.3
    - nodejs ==12.4.0  # [linux]
    - nodejs ==16.13.1  # [osx]
    - nomkl ==3.0  # [linux]
    - nose ==1.3.7
    - notebook ==6.4.6  # [linux or osx]
    - nspr ==4.32  # [linux or osx]
    - nss ==3.69  # [osx]
    - nss ==3.73  # [linux]
    - numba ==0.53.0  # [win]
    - numba ==0.54.1  # [linux or osx]
    - numexpr ==2.7.3  # [win]
    - numexpr ==2.8.0  # [linux or osx]
    - numpy ==1.20.3  # [linux or osx]
    - numpy ==1.21.4  # [win]
    - numpy-base ==1.20.3  # [linux or osx]
    - numpydoc ==1.1.0  # [linux or osx]
    - oauthlib ==3.1.1  # [linux or osx]
    - olefile ==0.46
    - openblas ==0.3.18  # [linux]
    - openssl ==1.1.1l
    - packaging ==21.3
    - pandas ==1.3.5
    - pandoc ==2.16.2  # [linux or osx]
    - pandocfilters ==1.5.0  # [linux or osx]
    - paramiko ==2.8.1
    - parso ==0.8.3
    - patchelf ==0.14.3  # [linux]
    - pcre ==8.45  # [linux or osx]
    - pexpect ==4.8.0
    - pickleshare ==0.7.5
    - pillow ==8.4.0
    - pip ==20.1.1
    - pkginfo ==1.8.2
    - platformdirs ==2.4.0  # [linux or osx]
    - plotly ==5.4.0  # [linux or osx]
    - pluggy ==0.13.1  # [win]
    - pluggy ==1.0.0  # [linux or osx]
    - prometheus_client ==0.12.0  # [linux or osx]
    - prompt-toolkit ==3.0.24
    - prompt_toolkit ==3.0.24  # [linux or osx]
    - psutil ==5.8.0
    - psycopg2 ==2.8.6  # [linux or win]
    - psycopg2 ==2.9.2  # [osx]
    - ptyprocess ==0.7.0  # [linux or osx]
    - py ==1.10.0  # [win]
    - py ==1.11.0  # [linux or osx]
    - py-lief ==0.11.5
    - pycodestyle ==2.8.0  # [linux or osx]
    - pycosat ==0.6.3
    - pycparser ==2.20
    - pycrypto ==2.6.1  # [linux or osx]
    - pyerfa ==2.0.0.1
    - pyflakes ==2.4.0  # [linux or osx]
    - pygments ==2.10.0
    - pyjwt ==2.0.1  # [linux or osx]
    - pylint ==2.12.2  # [linux or osx]
    - pynacl ==1.4.0
    - pyopenssl ==19.1.0
    - pyparsing ==3.0.6
    - pyqt ==5.12.3  # [osx or win]
    - pyqt ==5.9.2  # [linux]
    - pyqt-impl ==5.12.3  # [osx]
    - pyqt5-sip ==4.19.18  # [osx or win]
    - pyqtchart ==5.12  # [osx]
    - pyqtgraph ==0.11.1  # [linux]
    - pyqtgraph ==0.12.3  # [osx]
    - pyqtwebengine ==5.12.1  # [osx or win]
    - pyreadline ==2.1  # [win]
    - pyrsistent ==0.18.0  # [linux or osx]
    - pysocks ==1.7.1
    - pytables ==3.6.1
    - pytest ==6.2.4  # [win]
    - pytest ==6.2.5  # [linux or osx]
    - python ==3.8.3
    - python-dateutil ==2.8.2
    - python-docx ==0.8.11  # [linux or osx]
    - python-kaleido ==0.2.1  # [linux or osx]
    - python-libarchive-c ==3.2
    - python_abi ==3.8
    - pytz ==2021.3
    - pywin32 ==227  # [win]
    - pyyaml ==6.0
    - pyzmq ==22.3.0
    - qt ==5.12.5  # [win]
    - qt ==5.12.9  # [osx]
    - qt ==5.9.7  # [linux]
    - qtconsole ==5.2.2
    - qtpy ==1.11.3
    - readline ==8.1  # [linux or osx]
    - requests ==2.24.0
    - requests-oauthlib ==1.3.0  # [linux or osx]
    - requests-toolbelt ==0.9.1  # [linux or osx]
    - ripgrep ==13.0.0  # [linux or osx]
    - rope ==0.22.0  # [linux or osx]
    - ruamel_yaml ==0.15.87
    - scikit-learn ==1.0.1  # [linux or osx]
    - scipy ==1.7.3
    - secretstorage ==3.3.1  # [linux]
    - send2trash ==1.8.0  # [linux or osx]
    - setuptools ==49.2.0
    - setuptools-scm ==6.3.2
    - setuptools_scm ==6.3.2
    - sherpa ==4.12.2  # [linux or osx]
    - sip ==4.19.13  # [linux]
    - six ==1.15.0
    - smmap ==3.0.5
    - sniffio ==1.2.0  # [linux or osx]
    - snowballstemmer ==2.2.0
    - soupsieve ==2.3.1
    - sphinx ==4.3.1
    - sphinx-argparse ==0.3.1
    - sphinxcontrib-applehelp ==1.0.2
    - sphinxcontrib-devhelp ==1.0.2
    - sphinxcontrib-htmlhelp ==2.0.0
    - sphinxcontrib-jsmath ==1.0.1
    - sphinxcontrib-qthelp ==1.0.3
    - sphinxcontrib-serializinghtml ==1.1.5
    - sqlite ==3.32.3  # [win]
    - sqlite ==3.36.0  # [osx]
    - sqlite ==3.37.0  # [linux]
    - sqlparse ==0.4.2
    - tbb ==2021.4.0
    - tenacity ==8.0.1  # [linux or osx]
    - terminado ==0.12.1  # [linux or osx]
    - testpath ==0.5.0  # [linux or osx]
    - threadpoolctl ==3.0.0  # [linux or osx]
    - tk ==8.6.10  # [osx]
    - tk ==8.6.11  # [linux or win]
    - toml ==0.10.2
    - tomli ==2.0.0
    - tornado ==6.1
    - tqdm ==4.47.0
    - traitlets ==5.1.1
    - typing-extensions ==4.0.1  # [linux or osx]
    - typing_extensions ==4.0.1
    - tzdata ==2021e  # [linux or osx]
    - unicodedata2 ==13.0.0.post2
    - urllib3 ==1.25.9
    - vc ==14.1  # [win]
    - vs2015_runtime ==14.16.27012  # [win]
    - wcwidth ==0.2.5
    - webencodings ==0.5.1  # [linux or osx]
    - websocket-client ==1.2.3  # [linux or osx]
    - wheel ==0.34.2
    - widgetsnbextension ==3.5.2  # [linux or osx]
    - win_inet_pton ==1.1.0  # [win]
    - wincertstore ==0.2  # [win]
    - wrapt ==1.13.3  # [linux or osx]
    - xz ==5.2.5
    - yaml ==0.2.5
    - zeromq ==4.3.4  # [linux or osx]
    - zipp ==3.6.0
    - zlib ==1.2.11
    - zstd ==1.4.5  # [linux or win]
    - zstd ==1.5.0  # [osx]
