package:
  name: aperoll
  version:  {{ SKA_PKG_VERSION }}

build:
  script: pip install .

source:
  path: {{ SKA_TOP_SRC_DIR }}/aperoll


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - numpy
    - scipy
    - pyqt
    - pyqtwebengine
    - maude
    - chandra_aca
    - mica
    - cxotime
    - kadi
    - quaternion

test:
  imports:
    - aperoll


about:
  home: https://github.com/sot/aperoll
