package:
  name: ska3-builder
  version: {{ GIT_DESCRIBE_TAG }}

build:
  noarch: python
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/skare3


requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - ipython
    - pyyaml
    - gitpython
    - git
    - conda-build
    - ska3-pinned ==0.1
