package:
  name: ska.numpy
  version:  {{ SKA_PKG_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

source:
  path: {{ SKA_TOP_SRC_DIR }}/Ska.Numpy


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - gcc_linux-64==8.4.0 # [linux]
    - libgcc-ng==9.1.0  # [linux]
    - clang_osx-64 # [osx]
    - python==3.8.10
    - numpy
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - cython
    - ska_helpers
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - numpy
    - nose
    - testr
    - ska_helpers

test:
  imports:
    - Ska.Numpy


about:
  home: https://github.com/sot/Ska.Numpy

