package:
  name: ska3_builder
  version: 2018.08.11

build:
  noarch: generic

requirements:
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  build:
    - python
    - pip
    - gitpython
    - git
  run:
    - python
    - ipython
    - gitpython
    - git
    - conda ==4.3.21
    - conda-build ==3.0.19
    - conda-verify ==2.0.0
    - ska3-pinned ==2018.07.24
