package:
  name: ska3-perl
  version: 2018.11.27

requirements:
  run:
    - cfitsio ==3.450
    - xtime ==1.2.2
    - pgplot ==5.2.2 [linux]
    - perl ==5.26.2
    - perl-extutils-f77 ==1.20
    - perl-app-cpanminus ==1.7044
    - perl-core-deps ==0.1
    - perl-pgplot ==2.19 [linux]
    - perl-dbd-sybase ==1.15 [linux]
    - perl-chandra-time ==0.9.2
    - perl-app-env-ascds ==0.4
    - perl-cxc-sysarch ==1.0
    - perl-ska-agasc ==3.5.0
    - perl-ska-classic ==0.5
    - watch_cron_logs ==4.1
    - task_schedule ==4.1
    - starcheck ==12.0
