package:
  name: xija
  version:  {{ SKA_PKG_VERSION }}

build:
  script_env:
    - SKA_TOP_SRC_DIR

source:
  path: {{ SKA_TOP_SRC_DIR }}/xija


# the build and runtime requirements. Dependencies of these requirements
# are included automatically.
requirements:
  # Packages required to build the package. python and numpy must be
  # listed explicitly if they are required.
  build:
    - pip
    - python
    - setuptools
    - six
    - numba
    - numpy >=1.12.1
    - scipy
    - pyyaks
  # Packages required to run the package. These are the dependencies that
  # will be installed automatically whenever the package is installed.
  run:
    - python
    - six
    - scipy
    - numba
    - numpy >=1.12.1
    - matplotlib
    - ska.matplotlib
    - ska.numpy
    - pyyaks
    - chandra.time
    - testr

test:
  imports:
    - xija


about:
  home: https://github.com/sot/xija
