name: Upload Ska Package
on:
  workflow_call:

jobs:
  update-channel:
    runs-on: head
    name: Update Conda Channel
    steps:
      - name: Get linux package
        uses: actions/download-artifact@v2
        with:
          name: conda-package
          path: package
      - name: Update channel
        run: |
          rsync -a package/ ${CONDA_CHANNEL_DIR}
          for d in noarch linux-64 osx-64 win-64;
          do
            if [ -d "${CONDA_CHANNEL_DIR}/$d" ];
            then
              conda index ${CONDA_CHANNEL_DIR}/$d;
            fi
          done;
        env:
          CONDA_CHANNEL_DIR: /proj/sot/ska/www/ASPECT/ska3-conda/masters
