name: Deploy Ska Package Docs
on:
  workflow_call:
    inputs:
      repository:
        description: Repository to deploy docs from
        required: false
        type: string
        default: ${{ github.action_repository }}
    secrets:
      # This is the token used to push to the gh-pages branch
      # It is a personal access token with the repo scope
      token:
        required: true

jobs:
  build-linux:
    runs-on: head
    name: Deploy Docs
    steps:
      - name: Fetch source
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: source
          # this is so git fetches all metadata required by setuptools_scm to get the version
          fetch-depth: 0
      - name: Build docs
        run: |
          eval "$(/export/jgonzale/github-workflows/miniconda3-shiny/bin/conda shell.bash hook)"
          conda activate ska3-masters
          mkdir -p _static
          make html
        working-directory: source/docs
        env:
          PYTHONPATH: ${{ github.workspace }}/source
          GITHUB_API_TOKEN: ${{ secrets.token }}
          SKA: /proj/sot/ska
      - name: Fetch gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          path: gh-pages
          ref: gh-pages
          token: ${{ secrets.token }}
      - name: Replace docs
        run: |
          rm -fr gh-pages/docs/*
          cp -fr source/docs/_build/html/* gh-pages/docs
      - name: Commit changes
        run: |
          git config --global user.name 'Javier Gonzalez'
          git config --global user.email 'javierggt@yahoo.com'
          git add docs
          git commit -am "Deploy docs"
          git push
        working-directory: gh-pages
